<?php
/**
 * @author      Maciej Sławik <maciej.slawik@lizardmedia.pl>
 * Github:      https://github.com/maciejslawik
 */

//It is a good practise to create a PHPDoc with information about the class of the block
//that is injected into the view. This way your IDE will provide hints about available functions
/**
 * @var \LizardMedia\Sample\Block\Index $block
 */
?>
<?php
echo $block->getString();
